# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyPreviewer.ui'
#
# Created: Sun Sep 20 14:39:23 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(750, 0))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.splitter_2.setMouseTracking(False)
        self.splitter_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.splitter_2.setStyleSheet("")
        self.splitter_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_2.setLineWidth(1)
        self.splitter_2.setMidLineWidth(0)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.editorBox = QtWidgets.QGroupBox(self.splitter_2)
        self.editorBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editorBox.sizePolicy().hasHeightForWidth())
        self.editorBox.setSizePolicy(sizePolicy)
        self.editorBox.setMinimumSize(QtCore.QSize(0, 0))
        self.editorBox.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.editorBox.setTitle("")
        self.editorBox.setObjectName("editorBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.editorBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exampleView = QtWebKitWidgets.QWebView(self.editorBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exampleView.sizePolicy().hasHeightForWidth())
        self.exampleView.setSizePolicy(sizePolicy)
        self.exampleView.setUrl(QtCore.QUrl("about:blank"))
        self.exampleView.setObjectName("exampleView")
        self.horizontalLayout.addWidget(self.exampleView)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.previewerBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewerBox.sizePolicy().hasHeightForWidth())
        self.previewerBox.setSizePolicy(sizePolicy)
        self.previewerBox.setMinimumSize(QtCore.QSize(0, 0))
        self.previewerBox.setObjectName("previewerBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.previewerBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.previewerBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_2.addWidget(self.plainTextEdit_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.previewerBox_2 = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewerBox_2.sizePolicy().hasHeightForWidth())
        self.previewerBox_2.setSizePolicy(sizePolicy)
        self.previewerBox_2.setObjectName("previewerBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.previewerBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.previewerBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_3.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_3.setSizePolicy(sizePolicy)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout_4.addWidget(self.plainTextEdit_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.messagelineEdit = QtWidgets.QLineEdit(self.previewerBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messagelineEdit.sizePolicy().hasHeightForWidth())
        self.messagelineEdit.setSizePolicy(sizePolicy)
        self.messagelineEdit.setObjectName("messagelineEdit")
        self.horizontalLayout_7.addWidget(self.messagelineEdit)
        self.MessagepushButton = QtWidgets.QPushButton(self.previewerBox_2)
        self.MessagepushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.MessagepushButton.setObjectName("MessagepushButton")
        self.horizontalLayout_7.addWidget(self.MessagepushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ProgramRunButton = QtWidgets.QPushButton(self.previewerBox_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ProgramRunButton.setIcon(icon)
        self.ProgramRunButton.setObjectName("ProgramRunButton")
        self.horizontalLayout_3.addWidget(self.ProgramRunButton)
        self.ProgramStopButton = QtWidgets.QPushButton(self.previewerBox_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ProgramStopButton.setIcon(icon1)
        self.ProgramStopButton.setObjectName("ProgramStopButton")
        self.horizontalLayout_3.addWidget(self.ProgramStopButton)
        self.ClearButton = QtWidgets.QPushButton(self.previewerBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/locationbar_erase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClearButton.setIcon(icon2)
        self.ClearButton.setObjectName("ClearButton")
        self.horizontalLayout_3.addWidget(self.ClearButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuStyleSheet = QtWidgets.QMenu(self.menubar)
        self.menuStyleSheet.setObjectName("menuStyleSheet")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/New document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_File.setIcon(icon3)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionFile_Open = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/Folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFile_Open.setIcon(icon4)
        self.actionFile_Open.setObjectName("actionFile_Open")
        self.actionFile_Save = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFile_Save.setIcon(icon5)
        self.actionFile_Save.setObjectName("actionFile_Save")
        self.actionFile_Save_as = QtWidgets.QAction(MainWindow)
        self.actionFile_Save_as.setObjectName("actionFile_Save_as")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/Help book 3d.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon6)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_PyStudy = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/About.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_PyStudy.setIcon(icon7)
        self.actionAbout_PyStudy.setObjectName("actionAbout_PyStudy")
        self.actionRun = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/Go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon8)
        self.actionRun.setObjectName("actionRun")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setIcon(icon1)
        self.actionStop.setObjectName("actionStop")
        self.action_exit = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon9)
        self.action_exit.setObjectName("action_exit")
        self.action_example = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/Text preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_example.setIcon(icon10)
        self.action_example.setObjectName("action_example")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setIcon(icon2)
        self.actionClear.setObjectName("actionClear")
        self.actionPythonHelp = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/python-icon-help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPythonHelp.setIcon(icon11)
        self.actionPythonHelp.setObjectName("actionPythonHelp")
        self.actionStyleSheet_default = QtWidgets.QAction(MainWindow)
        self.actionStyleSheet_default.setObjectName("actionStyleSheet_default")
        self.actionStyleSheet_Black = QtWidgets.QAction(MainWindow)
        self.actionStyleSheet_Black.setObjectName("actionStyleSheet_Black")
        self.actionStyleSheet_Load = QtWidgets.QAction(MainWindow)
        self.actionStyleSheet_Load.setObjectName("actionStyleSheet_Load")
        self.action_myHome = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/img/24x24/Home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_myHome.setIcon(icon12)
        self.action_myHome.setObjectName("action_myHome")
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionFile_Open)
        self.menuFile.addAction(self.actionFile_Save)
        self.menuFile.addAction(self.actionFile_Save_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_myHome)
        self.menuFile.addAction(self.action_example)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_exit)
        self.menuHelp.addAction(self.actionPythonHelp)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout_PyStudy)
        self.menuRun.addAction(self.actionRun)
        self.menuRun.addAction(self.actionStop)
        self.menuRun.addAction(self.actionClear)
        self.menuStyleSheet.addAction(self.actionStyleSheet_default)
        self.menuStyleSheet.addAction(self.actionStyleSheet_Black)
        self.menuStyleSheet.addSeparator()
        self.menuStyleSheet.addAction(self.actionStyleSheet_Load)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuStyleSheet.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew_File)
        self.toolBar.addAction(self.actionFile_Open)
        self.toolBar.addAction(self.actionFile_Save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_example)
        self.toolBar_2.addAction(self.actionRun)
        self.toolBar_2.addAction(self.actionStop)
        self.toolBar_2.addAction(self.actionClear)
        self.toolBar_3.addAction(self.actionPythonHelp)
        self.toolBar_3.addAction(self.actionHelp)
        self.toolBar_3.addAction(self.actionAbout_PyStudy)
        self.toolBar_3.addAction(self.action_exit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyStudy 학습창"))
        self.previewerBox.setTitle(_translate("MainWindow", "소스 편집창"))
        self.previewerBox_2.setTitle(_translate("MainWindow", "프로그램실행창"))
        self.MessagepushButton.setText(_translate("MainWindow", "입력"))
        self.ProgramRunButton.setText(_translate("MainWindow", "실행"))
        self.ProgramStopButton.setText(_translate("MainWindow", "정지"))
        self.ClearButton.setText(_translate("MainWindow", "실행화면 초기화"))
        self.menuFile.setTitle(_translate("MainWindow", "파일"))
        self.menuHelp.setTitle(_translate("MainWindow", "도움말"))
        self.menuRun.setTitle(_translate("MainWindow", "소스실행기"))
        self.menuStyleSheet.setTitle(_translate("MainWindow", "스타일시트"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.actionNew_File.setText(_translate("MainWindow", "새 소스파일"))
        self.actionFile_Open.setText(_translate("MainWindow", "소스파일 열기"))
        self.actionFile_Save.setText(_translate("MainWindow", "소스파일 저장"))
        self.actionFile_Save_as.setText(_translate("MainWindow", "소스파일 다른이름으로 저장"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout_PyStudy.setText(_translate("MainWindow", "about PyStudy"))
        self.actionRun.setText(_translate("MainWindow", "실행"))
        self.actionStop.setText(_translate("MainWindow", "정지"))
        self.action_exit.setText(_translate("MainWindow", "창 닫기"))
        self.action_example.setText(_translate("MainWindow", "예제파일 열기"))
        self.actionClear.setText(_translate("MainWindow", "실행화면 초기화"))
        self.actionPythonHelp.setText(_translate("MainWindow", "파이썬도움말"))
        self.actionStyleSheet_default.setText(_translate("MainWindow", "default"))
        self.actionStyleSheet_Black.setText(_translate("MainWindow", "black"))
        self.actionStyleSheet_Load.setText(_translate("MainWindow", "스타일시트불러오기"))
        self.action_myHome.setText(_translate("MainWindow", "학습홈 바로가기"))

from PyQt5 import QtWebKitWidgets
import imageicon_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

